version: '3'
services:
  python:
    build: .
    image: python
    container_name: python
    working_dir: '/tmp/workspace'
    tty: true
    volumes:
      # - ./:/tmp/workspace
      - ./out:/tmp/workspace/out
      - ./src:/tmp/workspace/src
    privileged: true